# open redis 

FROM index.alauda.cn/openadmin/opencentos


RUN mkdir /data/server/nginx
RUN mkdir /data/server/nginx/src
RUN mkdir /data/log/nginx
WORKDIR /data/server/nginx


RUN wget -P http://download.redis.io/releases/redis-3.0.7.tar.gz